language: python

python:
  - "2.7"

# command to install system dependecies
before_install:
  - "sudo apt-get update -qq"

install:
  - "pip install -r requirements.txt"
  - "npm install -g grunt-cli"
  - "npm install -g bower"
  - "npm install"
  - "bower install"

# command to run tests
script: "./tests.sh"
